version: 0.0
os: linux

files:
  - source: /
    destination: /apps
    
hooks:  
  ApplicationStop:
    - location: Appstop.sh       
      #runas: root
  ApplicationStart:
    - location: . /apps/Appstart.sh
      #runas: root
